version: '3.8'

services:
  postgres:
    image: postgres:14  # You can specify the version you prefer
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"  # Expose the PostgreSQL port to your machine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data  # Persist data on host machine

volumes:
  postgres_data:
    driver: local
